package auth

import (
	"context"
	"crypto/sha256"
	"errors"
	"strings"
	"time"
)

// RefreshSession is the persistence representation of a refresh-token family.
// TokenDigest is the SHA-256 digest of the opaque token, never the token itself.
type RefreshSession struct {
	FamilyID    string
	UserID      UserID
	TokenDigest [sha256.Size]byte
	ExpiresAt   time.Time
	Consumed    bool
	Revoked     bool
}

type UserRepository interface {
	FindByEmail(context.Context, string) (CredentialRecord, error)
}

type RefreshSessionRepository interface {
	Create(context.Context, RefreshSession) error
	Rotate(context.Context, [sha256.Size]byte, RefreshSession) (RefreshSession, error)
	RevokeUser(context.Context, UserID) error
}

type PasswordVerifier interface {
	Verify(password, encodedHash string) (bool, error)
}
type AccessTokenIssuer interface {
	Issue(UserID) (IssuedAccessToken, error)
}
type RefreshTokenFactory func() (RefreshToken, error)

var (
	ErrAuthentication  = errors.New("authentication failed")
	ErrRefreshRejected = errors.New("refresh token rejected")
	ErrLogoutFailed    = errors.New("logout failed")
	ErrRepository      = errors.New("authentication repository failure")
)

// ServiceError is safe to expose at an API boundary: it contains a stable code
// and retry hint, while the wrapped cause remains available to errors.Is.
type ServiceError struct {
	Code      string
	Retryable bool
	cause     error
}

func (e *ServiceError) Error() string { return e.Code }
func (e *ServiceError) Unwrap() error { return e.cause }

type ServiceConfig struct {
	PasswordVerifier    PasswordVerifier
	AccessTokenIssuer   AccessTokenIssuer
	RefreshTokenFactory RefreshTokenFactory
	Users               UserRepository
	Sessions            RefreshSessionRepository
	Clock               func() time.Time
	RefreshLifetime     time.Duration
	OperationTimeout    time.Duration
}

type Service struct{ cfg ServiceConfig }

func NewService(cfg ServiceConfig) (*Service, error) {
	if cfg.PasswordVerifier == nil || cfg.AccessTokenIssuer == nil || cfg.RefreshTokenFactory == nil || cfg.Users == nil || cfg.Sessions == nil {
		return nil, errors.New("invalid auth service configuration")
	}
	if cfg.Clock == nil {
		cfg.Clock = time.Now
	}
	if cfg.RefreshLifetime <= 0 {
		cfg.RefreshLifetime = 30 * 24 * time.Hour
	}
	return &Service{cfg: cfg}, nil
}

func (s *Service) bounded(ctx context.Context) (context.Context, context.CancelFunc) {
	if s.cfg.OperationTimeout > 0 {
		return context.WithTimeout(ctx, s.cfg.OperationTimeout)
	}
	return context.WithCancel(ctx)
}

func normalizeEmail(email string) string { return strings.ToLower(strings.TrimSpace(email)) }

func (s *Service) Login(ctx context.Context, email, password string) (User, TokenPair, error) {
	ctx, cancel := s.bounded(ctx)
	defer cancel()
	record, err := s.cfg.Users.FindByEmail(ctx, normalizeEmail(email))
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"authentication_failed", false, ErrAuthentication}
	}
	if record.Status != UserStatusActive {
		return User{}, TokenPair{}, &ServiceError{"authentication_failed", false, ErrAuthentication}
	}
	ok, err := s.cfg.PasswordVerifier.Verify(password, record.PasswordHash)
	if err != nil || !ok {
		return User{}, TokenPair{}, &ServiceError{"authentication_failed", false, ErrAuthentication}
	}
	return s.issue(ctx, record.PublicUser())
}

func (s *Service) issue(ctx context.Context, user User) (User, TokenPair, error) {
	access, err := s.cfg.AccessTokenIssuer.Issue(user.ID)
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"token_issue_failed", true, err}
	}
	refresh, err := s.cfg.RefreshTokenFactory()
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"token_issue_failed", true, err}
	}
	expires := s.cfg.Clock().UTC().Add(s.cfg.RefreshLifetime)
	family := make([]byte, 16)
	// Family IDs are generated by the token factory's CSPRNG boundary in concrete wiring;
	// a digest-derived identifier remains non-secret and stable for simple adapters.
	digest := refresh.Digest()
	copy(family, digest[:])
	session := RefreshSession{FamilyID: string(family), UserID: user.ID, TokenDigest: refresh.Digest(), ExpiresAt: expires}
	if err := s.cfg.Sessions.Create(ctx, session); err != nil {
		return User{}, TokenPair{}, &ServiceError{"token_issue_failed", true, ErrRepository}
	}
	return user, TokenPair{AccessToken: access.Value, RefreshToken: refresh.Encoded(), AccessExpiresAt: access.ExpiresAt, RefreshExpiresAt: expires}, nil
}

func (s *Service) Refresh(ctx context.Context, presentedOpaqueToken string) (User, TokenPair, error) {
	ctx, cancel := s.bounded(ctx)
	defer cancel()
	presented, err := ParseRefreshToken(presentedOpaqueToken)
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"refresh_rejected", false, ErrRefreshRejected}
	}
	replacement, err := s.cfg.RefreshTokenFactory()
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"token_issue_failed", true, err}
	}
	next := RefreshSession{TokenDigest: replacement.Digest(), ExpiresAt: s.cfg.Clock().UTC().Add(s.cfg.RefreshLifetime)}
	current, err := s.cfg.Sessions.Rotate(ctx, presented.Digest(), next)
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"refresh_rejected", false, ErrRefreshRejected}
	}
	access, err := s.cfg.AccessTokenIssuer.Issue(current.UserID)
	if err != nil {
		return User{}, TokenPair{}, &ServiceError{"token_issue_failed", true, err}
	}
	return User{ID: current.UserID, Status: UserStatusActive}, TokenPair{AccessToken: access.Value, RefreshToken: replacement.Encoded(), AccessExpiresAt: access.ExpiresAt, RefreshExpiresAt: next.ExpiresAt}, nil
}

func (s *Service) Logout(ctx context.Context, userID UserID) error {
	ctx, cancel := s.bounded(ctx)
	defer cancel()
	if strings.TrimSpace(string(userID)) == "" {
		return &ServiceError{"logout_failed", false, ErrLogoutFailed}
	}
	if err := s.cfg.Sessions.RevokeUser(ctx, userID); err != nil {
		return &ServiceError{"logout_failed", true, ErrLogoutFailed}
	}
	return nil
}
